name: SSH to Remote Machine

on:
  push:
    branches:
      - main

jobs:
  ssh-and-run-command:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH key
      run: |
        # Save the SSH private key from GitHub Secrets
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
        chmod 600 private_key.pem

    - name: SSH and run command
      run: |
        ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i private_key.pem ubuntu@ec2-52-77-254-51.ap-southeast-1.compute.amazonaws.com 'ls -lh'
